### ISSUE TITLE
GetSchema implementation does not work

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-component-provider-py-boilerplate#15]
Trying to follow along with the component provider boilerplate example and have successfully installed the built plugin using pulumi plugin install resource xyz 0.0.1 -f ../pulumi-component-provider-py-boilerplate/dist/pulumi-resource-xyz-v0.0.1-darwin-amd64.tar.gz  but at this point im still a bit unclear how to use the plugin.  My Pulumi.yaml looks like this:

```yaml
name: HelloApp
runtime:
  name: yaml
description: A minimal Yaml Pulumi program

resources:
  mysite:
    type: xyz:index:StaticPage

```

 and running a preview gives me an error:

```
    error resolving type of resource mysite: internal error loading package "xyz": could not read plugin [/Users/acme/.pulumi/plugins/resource-xyz-v0.0.1/pulumi-resource-xyz] stdout: EOF 
error: an unhandled error occurred: failed to evaluate template
```

This is because the `GetSchema` implementation throws an error - because it uses os.path.dir instead of os.path.dirname.
